-- staging
CREATE DATABASE staging;
CREATE USER staging WITH ENCRYPTED PASSWORD 'sta12ging';
GRANT ALL PRIVILEGES ON DATABASE staging TO staging;

-- datawarehouse
CREATE DATABASE datawarehouse;
CREATE USER dwhouse WITH ENCRYPTED PASSWORD 'dw123';
GRANT ALL PRIVILEGES ON DATABASE datawarehouse TO dwhouse;

-- datamart
CREATE DATABASE datamart;
CREATE USER mart WITH ENCRYPTED PASSWORD 'm12art';
GRANT ALL PRIVILEGES ON DATABASE datamart TO mart;

-- control
CREATE DATABASE control;
CREATE USER control WITH ENCRYPTED PASSWORD 'c12on';
GRANT ALL PRIVILEGES ON DATABASE control TO control;

